spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movies
    username: root
    password: Password_1264
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: naveenkap17@gmail.com
    password: 
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

project:
  poster: posters/
  base:
    url: "http://localhost:8080"
